name: Run Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: apache/camel-quarkus
          ref: master
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        env:
          MAVEN_OPTS: -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        run: ./mvnw $MAVEN_OPTS clean install
  it1:
    name: IT-1
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: IT
        env:
          MAVEN_OPTS: -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        run: ./mvnw $MAVEN_OPTS clean verify -Dnative -Ddocker -pl :camel-quarkus-integration-test-core
