name: Run Integration Tests

on:
  pull_request:
    branches:
      - master
env:
  LANG: en_US

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: apache/camel-quarkus
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: |
          ./mvnw -V -B \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            clean install
      - name: Save Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ github.sha }}
          restore-keys: |
            maven-${{ github.sha }}
  # core:
  #   name: core
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-core \
  #           -pl :camel-quarkus-integration-test-core-impl \
  #           -pl :camel-quarkus-integration-test-core-main \
  #           -pl :camel-quarkus-integration-test-core-main-collector \
  #           -pl :camel-quarkus-integration-test-core-main-xml
  # foundation:
  #   name: foundation
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-bean \
  #           -pl :camel-quarkus-integration-test-seda \
  #           -pl :camel-quarkus-integration-test-file \
  #           -pl :camel-quarkus-integration-test-scheduler \
  #           -pl :camel-quarkus-integration-test-jsonpath \
  #           -pl :camel-quarkus-integration-test-exec \
  #           -pl :camel-quarkus-integration-test-controlbus \
  #           -pl :camel-quarkus-integration-test-hystrix
  # platform:
  #   name: platform
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-platform-http \
  #           -pl :camel-quarkus-integration-test-platform-http-engine \
  #           -pl :camel-quarkus-integration-test-microprofile \
  #           -pl :camel-quarkus-integration-test-opentracing
  # messaging:
  #   name: messaging
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-sjms \
  #           -pl :camel-quarkus-integration-test-kafka \
  #           -pl :camel-quarkus-integration-test-paho
  # dataformats:
  #   name: dataformats
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-base64 \
  #           -pl :camel-quarkus-integration-test-snakeyaml \
  #           -pl :camel-quarkus-integration-test-tagsoup \
  #           -pl :camel-quarkus-integration-test-xslt \
  #           -pl :camel-quarkus-integration-test-csv \
  #           -pl :camel-quarkus-integration-test-jackson \
  #           -pl :camel-quarkus-integration-test-dataformat
  # networking:
  #   name: networking
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-http \
  #           -pl :camel-quarkus-integration-test-netty \
  #           -pl :camel-quarkus-integration-test-servlet
  # sql:
  #   name: sql
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-jdbc \
  #           -pl :camel-quarkus-integration-test-mongodb \
  #           -pl :camel-quarkus-integration-test-sql
  # cloud:
  #   name: cloud
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-aws \
  #           -pl :camel-quarkus-integration-test-consul
  # misc:
  #   name: misc
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -pl :camel-quarkus-integration-test-bean-validator \
  #           -pl :camel-quarkus-integration-test-dozer \
  #           -pl :camel-quarkus-integration-test-ftp \
  #           -pl :camel-quarkus-integration-test-infinispan \
  #           -pl :camel-quarkus-integration-test-mail \
  #           -pl :camel-quarkus-integration-test-pdf \
  #           -pl :camel-quarkus-integration-test-salesforce \
  #           -pl :camel-quarkus-integration-test-slack \
  #           -pl :camel-quarkus-integration-test-tarfile \
  #           -pl :camel-quarkus-integration-test-twitter \
  #           -pl :camel-quarkus-integration-test-validator \
  #           -pl :camel-quarkus-integration-test-zipfile
  # memoryhogs:
  #   name: memoryhogs
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: apache/camel-quarkus
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     # run the :camel-quarkus-integration-test-fhir as standalone process
  #     # as it building the native image including camel-fhir requires lot 
  #     # of memory this we nee to limit it to avoid the process fail for OOM.
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -Dnative-image.xmx=5g \
  #           -pl :camel-quarkus-integration-test-fhir
             
