name: OpenShift

on:
  pull_request:
    branches:
      - master

jobs:
  example:
    name: OpenShift Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.0.0
        with:
          oc version: 'v3.11.0'
      - name: Interact with the cluster
        run: oc cluster status


