name: Run Integration Tests With Options

on:
  pull_request:
    branches:
      - master

env:
  LANG: en_US

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set BRANCH_OPTIONS
        if: github.base_ref == 'master'
        run: |
          echo '::set-env name=BRANCH_OPTIONS::"-Dquarkus.version=999-SNAPSHOT -Poss-snapshots"'
      - name: Echo
        run: |
          echo ${BRANCH_OPTIONS}
          echo ${GITHUB_REF}
          echo ${GITHUB_BASE_REF}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: apache/camel-quarkus
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: |
          ./mvnw ${BRANCH_OPTIONS} -V -B \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -DskipTests \
            clean install
