name: run

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: ubuntu-22.04
    steps:
      - name: "Skopeo"
        run: |    
          export XDG_RUNTIME_DIR=$HOME/.config
          skopeo --version
          skopeo inspect docker://busybox:latest
