name: run

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        overlay:
          - "dev"
    steps:
      - name: "Checkout cos-manifests project"
        uses: actions/checkout@v2
        with:
          repository: bf2fc6cc711aee1a0c2a/cos-manifests
      - name: "Update Kustomize overlay ${{ matrix.overlay }}"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/data-plane
          DEPLOY_TAG: '0.1.29'
        run: |          
          for APP in cos-fleetshard-sync cos-fleetshard-operator-camel cos-fleetshard-operator-debezium; do
              export IMAGE=quay.io/rhoas/${APP}
              export SHA256=$(docker manifest inspect ${IMAGE}:${DEPLOY_TAG} | jq -r '.config.digest')
              
              yq -i '.images[] |= select(.name == strenv(IMAGE)).digest = strenv(SHA256)' ${OVERLAY_PATH}/kustomization.yaml
              yq -i 'del(.images[] |= select(.name == strenv(IMAGE)).newTag)' ${OVERLAY_PATH}/kustomization.yaml
          done
      - name: "Show"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/data-plane
        run: |
          cat ${OVERLAY_PATH}/kustomization.yaml
