name: run

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
  BRANCH_NAME: release-${{ github.ref_name }}-${{ github.sha }}

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "COS_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "COS_REVISION=${GITHUB_SHA}" >> $GITHUB_ENV
      - run: |
          echo "$COS_VERSION"
          echo "$COS_REVISION"
