name: run

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        overlay:
          - "dev"
    steps:
      - name: "Install Software"
        uses: actions/checkout@v2
        with:
          cmd: |
            sudo apt-get -y install skopeo jq yq
      - name: "Check Software"
        uses: actions/checkout@v2
        with:
          cmd: |
            docker version
            jq -V
            yq -V
      - name: "Checkout cos-manifests project"
        uses: actions/checkout@v2
        with:
          repository: bf2fc6cc711aee1a0c2a/cos-manifests
      - name: "Update Kustomize overlay ${{ matrix.overlay }}"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}/data-plane
          DEPLOY_TAG: '0.1.29'
        with:
          cmd: |
            export SHA256_SYNC=$(skopeo inspect docker://quay.io/rhoas/cos-connector-mongodb:${DEPLOY_TAG} --format "{{.Digest}}")
            export SHA256_CAMEL=$(skopeo inspect docker://quay.io/rhoas/cos-connector-cassandra:${DEPLOY_TAG} --format "{{.Digest}}")
            export SHA256_DEBEZIUM=$(skopeo inspect docker://quay.io/rhoas/cos-connector-elasticsearch:${DEPLOY_TAG} --format "{{.Digest}}")

            yq -i '.images[] |= select(.name == "quay.io/rhoas/cos-fleetshard-sync").digest = strenv(SHA256_SYNC)' ${OVERLAY_PATH}/kustomization.yaml
            yq -i '.images[] |= select(.name == "quay.io/rhoas/cos-fleetshard-operator-camel").digest = strenv(SHA256_CAMEL)' ${OVERLAY_PATH}/kustomization.yaml
            yq -i '.images[] |= select(.name == "quay.io/rhoas/cos-fleetshard-operator-debezium").digest = strenv(SHA256_DEBEZIUM)' ${OVERLAY_PATH}/kustomization.yaml

      - name: "Show"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ matrix.overlay }}
        run: |
          cat ${OVERLAY_PATH}/kustomization.yaml
