name: run

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: ubuntu-22.04
    steps:
      - name: "Skopeo"
        run: |    
          skopeo --version
          skopeo inspect --no-creds --no-tags docker://busybox:latest
